"""add uid column

Revision ID: 719a693dd814
Revises: cdda9cd6aeb1
Create Date: 2025-07-25 16:59:16.952558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '719a693dd814'
down_revision: Union[str, Sequence[str], None] = 'cdda9cd6aeb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uid', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'uid')
    # ### end Alembic commands ###
